version: '3.0'

networks: {rasa-network: {}}

services:

  engine:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./storage/engine/:/app/"
    entrypoint: /app/main
    command: >
      exec
      -subArgs --version
    # environment:
    # - HTTPPORT=5000

  actions:
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./storage/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

  # region: obsolete

  # proxy:
  #   image: nginx:latest
  #   networks: ['rasa-network']
  #   ports:
  #   - "8443:443"
  #   volumes:
  #   - "./storage/proxy/:/etc/nginx/conf.d"
  #   depends_on:
  #   - agentDefault
  #   - mgmt

  # endregion: obsolete
