version: '3.0'

services:

  mgmt:
    image: alpine:latest
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./storage/:/srv/"
    command: >
      /srv/mgmt/main
      -httpStaticRoot /srv/mgmt/public
      -httpStaticEnabled true

  agentDefault:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5001:5005"
    volumes:
    - "./storage/agentDefault/:/app/"
    command: >
      run
      --enable-api
      --cors "*"
      --debug
  agent2:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5002:5005"
    volumes:
    - "./storage/agent2/:/app/"
    command: >
      run
      --enable-api
      --cors "*"
      --debug
  agent3:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5003:5005"
    volumes:
    - "./storage/agent3/:/app/"
    command: >
      run
      --enable-api
      --cors "*"
      --debug

  actions:
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./storage/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}
